"""empty message

Revision ID: 3462037a4b14
Revises: c397a66b1650
Create Date: 2022-07-27 15:59:07.838149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3462037a4b14'
down_revision = 'c397a66b1650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ballots', 'voted_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('ballots_voter_id_fkey', 'ballots', type_='foreignkey')
    op.drop_constraint('districts_voter_id_fkey', 'districts', type_='foreignkey')
    op.drop_constraint('pacs_voter_id_fkey', 'pacs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pacs_voter_id_fkey', 'pacs', 'voters', ['voter_id'], ['id'])
    op.create_foreign_key('districts_voter_id_fkey', 'districts', 'voters', ['voter_id'], ['id'])
    op.create_foreign_key('ballots_voter_id_fkey', 'ballots', 'voters', ['voter_id'], ['id'])
    op.alter_column('ballots', 'voted_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
