"""empty message

Revision ID: d4e6ee0d4ab0
Revises: 8592ac750f69
Create Date: 2022-07-30 11:21:09.557363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e6ee0d4ab0'
down_revision = '8592ac750f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ballots', 'voters', ['voter_id'], ['id'])
    op.create_foreign_key(None, 'districts', 'voters', ['voter_id'], ['id'])
    op.create_foreign_key(None, 'pacs', 'voters', ['voter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacs', type_='foreignkey')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_constraint(None, 'ballots', type_='foreignkey')
    # ### end Alembic commands ###
