"""empty message

Revision ID: 68bda82a44bb
Revises: 67abb77b6b01
Create Date: 2022-07-26 12:49:01.540310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bda82a44bb'
down_revision = '67abb77b6b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('voted_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballots', 'voted_on')
    # ### end Alembic commands ###
