"""empty message

Revision ID: 34c81522fe98
Revises: 
Create Date: 2022-07-26 12:28:13.937184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c81522fe98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacs_voters',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('pac_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pac_id'], ['pacs.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'pac_id')
    )
    op.drop_table('voters_pacs')
    op.add_column('accounts', sa.Column('party_affiliation', sa.String(length=128), nullable=False))
    op.drop_constraint('accounts_voter_id_key', 'accounts', type_='unique')
    op.drop_column('accounts', 'party_affilliation')
    op.drop_constraint('ballots_voter_id_key', 'ballots', type_='unique')
    op.alter_column('candidates', 'party',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('districts_voter_id_key', 'districts', type_='unique')
    op.alter_column('pacs', 'issue',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('pacs_name_key', 'pacs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pacs_name_key', 'pacs', ['name'])
    op.alter_column('pacs', 'issue',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('districts_voter_id_key', 'districts', ['voter_id'])
    op.alter_column('candidates', 'party',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('ballots_voter_id_key', 'ballots', ['voter_id'])
    op.add_column('accounts', sa.Column('party_affilliation', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('accounts_voter_id_key', 'accounts', ['voter_id'])
    op.drop_column('accounts', 'party_affiliation')
    op.create_table('voters_pacs',
    sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pac_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pac_id'], ['pacs.id'], name='fk_voters_pacs_pacs'),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name='fk_voters_pacs_voters'),
    sa.PrimaryKeyConstraint('voter_id', 'pac_id', name='voters_pacs_pkey')
    )
    op.drop_table('pacs_voters')
    # ### end Alembic commands ###
